TudoBuffet.Website/Models/PartyOwnerViewModel.cs
using System.Collections.Generic;
using TudoBuffet.Website.Entities;

namespace TudoBuffet.Website.Models
{
    public class PartyOwnerViewModel
    {
        public PartyOwnerViewModel()
        {
            Budgets = new List<BudgetModel>();
        }

        public List<BudgetModel> Budgets { get; set; }
        public string OwnerName { get; set; }

        public void AddBudget(IEnumerable<Budget> budgets)
        {
            foreach (var budget in budgets)
            {
                foreach (var detail in budget.Details)
                {
                    Budgets.Add(new BudgetModel()
                    {
                        PartyDay = budget.PartyDay,
                        QuantityGuests = budget.QuantityPartyGuests,
                        Detail = CreateDetail(detail)
                    });
                }
            }
        }

        private BudgetDetailModel CreateDetail(BudgetDetail detail)
        {
            return new BudgetDetailModel()
            {
                BuffetName = detail.Buffet.Name,
                IsDateAvailable = detail.IsDateAvaliable.HasValue ? detail.IsDateAvaliable.Value : true,
                DetailId = detail.Id,
                Title = detail.Buffet.Title,
                WasAnswered = detail.AnsweredAt.HasValue
            };
        }
    }
}

TudoBuffet.Website/Controllers/PartyOwnerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using TudoBuffet.Website.Entities;
using TudoBuffet.Website.Models;
using TudoBuffet.Website.Repositories.Contracts;

namespace TudoBuffet.Website.Controllers
{
    [Route("dono-da-festa")]
    [Authorize(Roles = "UserPartyOwner")]
    public class PartyOwnerController : AuthenticatedControllerBase
    {
        private readonly IBudgets budgets;

        public PartyOwnerController(IBudgets budgets)
        {
            this.budgets = budgets;
        }

        public IActionResult Index()
        {
            PartyOwnerViewModel adminPartyOwner;
            IEnumerable<Budget> budgetsFound;

            budgetsFound = budgets.GetByUserId(UserId);

            adminPartyOwner = new PartyOwnerViewModel();
            adminPartyOwner.AddBudget(budgetsFound);

            return View(adminPartyOwner);
        }
    }
}

TudoBuffet.Website/Views/PartyOwner/Index.cshtml
@model TudoBuffet.Website.Models.PartyOwnerViewModel
@{
    ViewData["Title"] = "Gerencie seus orçamentos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        @await Html.PartialAsync("~/Views/Shared/_PartialMenuPartyOwner.cshtml")
        <div id="customer-orders" class="col-lg-9">
            <div class="box">
                <h1>Orçamentos</h1>
                <p class="lead">Bem-vindo, @Model.OwnerName</p>
                <p class="text-muted">Se houver algum problema, entre em <a href="contact.html">contato</a>, responderemos o mais breve possível.</p>
                <div class="table-responsive">
                    @foreach (var budget in Model.Budgets)
                    {
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th colspan="4">Quantidade de convidados: @budget.QuantityGuests | Data da festa: @budget.PartyDay.ToString("dd/MM/yyyy")</th>
                                </tr>
                                <tr>
                                    <th>Nome buffet</th>
                                    <th>Foi respondido</th>
                                    <th>Está disponível na data</th>
                                    <th>Nova data proposta</th>
                                    <th>Ver respostas</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><a href="~/buffets/@budget.Detail.Title">@budget.Detail.BuffetName</a></td>
                                    <td>@(budget.Detail.WasAnswered ? "Sim" : "Ainda não") </td>
                                    <td>@(budget.Detail.IsDateAvailable ? "Sim" : "Não" )</td>
                                    <td>@(budget.Detail.IsDateAvailable ? "-" : budget.Detail.ProposedDateFor.ToString("dd/MM/yyyy") )</td>
                                    <td>@(budget.Detail.WasAnswered ? @Html.ActionLink("Ver respostas", "Answers", "PartyOwner", new { id = budget.Detail.DetailId }, null) : Html.Raw(" - ") )</td>
                                </tr>
                            </tbody>
                        </table>
                    }
                </div>
            </div>
        </div>
    </div>
</div>